name: CodSpeed

on:
  push:
    branches:
      - master
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions: {}

env:
  UV_NO_SYNC: true

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      # Required for OpenID Connect authentication with CodSpeed
      id-token: write
    env:
      UV_PYTHON: "3.13"
      UV_RESOLUTION: highest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.13"
      - name: Setup uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          version: "latest-known"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock
      - name: Install Dependencies
        run: uv sync --no-dev --group tests --extra all
      - name: CodSpeed benchmarks
        uses: CodSpeedHQ/action@373d6868929f444bc08d901fd0eb0ad52a8875ea # v5.2.1
        with:
          mode: simulation
          run: uv run --no-sync pytest tests/benchmarks --codspeed
      - name: CodSpeed memory benchmarks
        uses: CodSpeedHQ/action@373d6868929f444bc08d901fd0eb0ad52a8875ea # v5.2.1
        with:
          mode: memory
          run: uv run --no-sync pytest tests/memory_benchmarks --codspeed
